# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://mtbarta.github.io/monocorpus
title: MonoCorpus
email: matt@monocorpus.com
author: Matt Barta
description: > # "Write an awesome description for your new site here. 
  Note Taking Application for Software Engineers and Machine Learning
  practitioners. Take notes, share them, learn and work faster.
copyright: 'Copyright &copy; 2018 Matt Barta. All Rights Reserved.'
credits: 'Credits: Thanks to Shane for <a href="https://github.com/swcool/landing-page-theme">landing-page-theme</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/mtbarta/monocorpus

about: >
  MonoCorpus is a note taking app for software and machine learning engineers
  meant to encourage learning, sharing, and easier development.
  <p>
  This is the place to keep track of thoughts that don't directly relate
  to the issue in your ticket, the flow of code that you figured out
  after debugging it a few times, and ideas that came from your sprint kickoff.
  Consider it a cache for your development process.
  </p>
  <p>
  Catch yourself back up on a project that was sidelined for a month. Lookup the fix
  for a bug that inexplicably is back in production. Remeber the order of Jupyter Notebooks
  you need to run to repeat your experiment.
  </p>
  <p>
  All of your ideas in one place.
  </p>

