# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://mtbarta.github.io/monocorpus
title: MonoCorpus
email: matt@monocorpus.com
author: Matt Barta
description: > # "Write an awesome description for your new site here. 
  Note Taking Application for Software Engineers and Machine Learning
  practitioners. Take notes, share them, learn and work faster.
copyright: 'Copyright &copy; 2018 Matt Barta. All Rights Reserved.'
credits: 'Credits: Thanks to Shane for <a href="https://github.com/swcool/landing-page-theme">landing-page-theme</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/mtbarta/monocorpus

about: >
  MonoCorpus is a note taking app for software and machine learning engineers
  meant to encourage learning, sharing, and easier development.
  <p>
  Increase documentation for yourself and your team without slowing
  your velocity. Take notes as part of your process instead of dedicating
  time to writing it.
  </p>
  <p>
  Instantly ramp up on projects.
  </p>

