version: "3.4"
networks:
  web:
  backend:
services:
  postgres:
    image: postgres:10.1-alpine
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: login
    volumes:
      # - ./login/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - '$POSTGRES_DATA_LOC:/var/lib/postgresql/data'
    networks:
      - backend
    labels:
      - "traefik.enable=false"
  mongo:
    image: mongo:3.6.2-jessie
    restart: always
    volumes:
      - '$MONGO_DATA_LOC:/data/db'
    networks:
      - backend
    labels:
      - "traefik.enable=false"
    healthcheck:
      test: "mongo --quiet localhost/notes --eval 'quit(db.runCommand({ ping: 1}).ok ? 0 : 2)' || exit 1"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
  notes:
    image: notes:latest
    restart: always
    environment:
      - PORT=8889
      - HTTPPORT=8888
      - DBHOST=mongo
      - DBPORT=27017
      - DBNAME=notes
      - COLLECTION=store
    networks:
      - backend
    healthcheck:
      test: ["CMD", "/go/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
  search:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2
    restart: always
    environment:
      - "discovery.type=single-node"
    volumes:
      - "$SEARCH_DATA_LOC:/usr/share/elasticsearch/data"
    networks:
      - backend
    labels:
      - "traefik.enable=false"
    healthcheck:
      test: curl localhost:9200/_cat/health?pretty || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
  gateway:
    image: gateway:latest
    restart: always
    environment:
      LOGINHOST: login
      LOGINPORT: 8888
      NOTESHOST: notes
      NOTESPORT: 8889
      SEARCHHOST: search
      SEARCHPORT: 9200
      SEARCHINDEX: notes
      SEARCHTYPE: note
      PORT: 8081
      PUBKEY: "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0fJj+S5cyjKEbPLH08bi4zcseRXFI4YmDI/eRDHLqZzqTsjzICs6owMH3QV0fDP8J2ADuPjswZX+MBkmIvk/dSXBJ6J4mHF+G6b9yKtVh5Jz071qpkkRlGZS4yj0cDMftVPM+Q0I1ReAeEBnUqrxiD5OMiTW2u3kOfkLVnQvglsiP3+abwPS4DPP9uc23KyRoM/aJDJkJ+ySo64Q/Dh0Ufkqhw1IOAIaeW31bgm+piVEU/60AOFu8DHpoGrHY/4EZPU446Id+Qb/d1IGEJwR63uQU3DjAGP7Dao3VvNp5NOjy6VnaSDzuL7F3qfnC0VLmruMioqN2Wyoslfda6t+LwIDAQAB\n-----END PUBLIC KEY-----"
    healthcheck:
      test: ["CMD", "/go/bin/healthcheck"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    depends_on:
      - search
      - notes
    networks:
      - web
      - backend
    labels:
      - "traefik.backend=gateway"
      - "traefik.docker.network=${NETWORK}_web"
      - "traefik.frontend.rule=PathPrefix:/notes;Host:$HOST"
      - "traefik.enable=true"
      - "traefik.port=8081"
  keycloak:
    image: jboss/keycloak-postgres:4.0.0.Beta1
    restart: always
    environment:
      - PROXY_ADDRESS_FORWARDING=true
      - POSTGRES_ADDR=postgres
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DATABASE=login
      - KEYCLOAK_USER=$KEYCLOAK_USER
      - KEYCLOAK_PASSWORD=$KEYCLOAK_PASSWORD
    # ports:
    #   - 8090:8080
    depends_on:
      - postgres
    networks:
      - web
      - backend
    labels:
      - "traefik.backend=keycloak"
      - "traefik.docker.network=${NETWORK}_web"
      - "traefik.frontend.rule=PathPrefix:/auth;Host:$HOST"
      - "traefik.enable=true"
      - "traefik.port=8080"
      # - "traefik.admin.frontend.rule=PathPrefix:/auth/admin;Host:$HOST"
      # - "traefik.admin.protocol=https"
      # - "traefik.admin.whitelist.sourceRange=73.169.138.154"
    healthcheck:
      test: curl localhost:8080/auth
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
  frontend:
    image: frontend:latest
    restart: always
    networks:
      - web
      - backend
    # ports:
    #   - "8091:80"
    labels:
      - "traefik.backend=frontend"
      - "traefik.docker.network=${NETWORK}_web"
      - "traefik.frontend.rule=PathPrefix:/;Host:$HOST"
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.default.protocol=http"
      - "traefik.passHostHeader=true"
    healthcheck:
      test: curl --fail localhost
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
  traefik:
    image: traefik:1.5.4-alpine
    container_name: traefik
    restart: always
    command: --docker  --api
    ports:
      - "80:80"     #The HTTP port
      - "443:443"
      - "8080:8080" #The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock #So that Traefik can listen to the Docker events
      - ../services/src/monocorpus/traefik/${ENV}.traefik.toml:/traefik.toml:ro
      - ./traefik/acme.json:/acme.json
    networks:
      - web
    labels:
      - "traefik.frontend.rule=Host:$HOST"