version: "3.4"
networks:
  web:
  backend:
services:
  postgres:
    image: postgres:10.1-alpine
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: login
    volumes:
      - '$POSTGRES_DATA_LOC:/var/lib/postgresql/data'
    networks:
      - backend
    labels:
      - "traefik.enable=false"
  mongo:
    image: monocorpus/mongo:3.6.2-jessie
    restart: always
    volumes:
      - '$MONGO_DATA_LOC:/data/db'
    networks:
      - backend
    environment:
      CONSUL_JOIN: consul
      CONSUL_DC: dc1
      CONSUL_SERVICE_NAME: mongo
    labels:
      - "traefik.enable=false"
    healthcheck:
      test: "mongo --quiet localhost/notes --eval 'quit(db.runCommand({ ping: 1}).ok ? 0 : 2)' || exit 1"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
      
  consul:
    # needs to map volumes!
    image: consul:1.2.2
    container_name: consul
    command: agent -ui -server -client 0.0.0.0 -bind 0.0.0.0 -bootstrap-expect=1
    networks:
      - backend
    dns: consul
    dns_search: service.consul
    labels:
      - "traefik.enable=false"

  notes:
    image: notes:latest
    restart: always
    environment:
      - DBHOST=mongo
      - DBPORT=27017
      - DBNAME=notes
      - COLLECTION=store
      - MICRO_REGISTRY_ADDRESS=consul:8500
    networks:
      - backend
    dns: consul
    dns_search: service.consul
    depends_on:
      - mongo
      - consul
    labels:
      - "traefik.enable=false"

  search:
    image: search:latest
    restart: always
    environment:
      COLLECTION: store
      MICRO_REGISTRY_ADDRESS: consul:8500
      SEARCHINDEX: notes
      SEARCHTYPE: note
    networks:
      - backend
    dns: consul
    dns_search: service.consul
    depends_on:
      - elasticsearch
      - consul
    labels:
      - "traefik.enable=false"

  elasticsearch:
    image: monocorpus/elasticsearch:6.2.2-oss
    restart: always
    environment:
      - "discovery.type=single-node"
      - "CONSUL_JOIN=consul"
      - "CONSUL_DC=dc1"
      - "CONSUL_SERVICE_NAME=elasticsearch"
    volumes:
      - "$SEARCH_DATA_LOC:/usr/share/elasticsearch/data"
    networks:
      - backend
    labels:
      - "traefik.enable=false"
    healthcheck:
      test: curl localhost:9200/_cat/health?pretty || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  gateway:
    image: gateway:latest
    restart: always
    environment:
      SEARCHINDEX: notes
      SEARCHTYPE: note
      HTTPPORT: 8081
      MICRO_REGISTRY_ADDRESS: consul:8500
      CLIENTID: notebook
      ISSUERURL: http://$HOST/auth/realms/Notes
      JWKSURL: http://keycloak:8080/auth/realms/Notes/protocol/openid-connect/certs
    healthcheck:
      test: ["CMD", "/go/bin/healthcheck"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    depends_on:
      - notes
    networks:
      - web
      - backend
    dns: consul
    dns_search: service.consul
    labels:
      - "traefik.backend=gateway"
      - "traefik.docker.network=${NETWORK}_web"
      - "traefik.frontend.rule=PathPrefix:/notes;Host:$HOST"
      - "traefik.enable=true"
      - "traefik.port=8081"
      
  keycloak:
    image: keycloak:latest
    restart: always
    environment:
      - DB_VENDOR=POSTGRES
      - PROXY_ADDRESS_FORWARDING=true
      - POSTGRES_ADDR=postgres
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DATABASE=login
      - KEYCLOAK_USER=$KEYCLOAK_USER
      - KEYCLOAK_PASSWORD=$KEYCLOAK_PASSWORD
    depends_on:
      - postgres
    networks:
      - web
      - backend
    labels:
      - "traefik.backend=keycloak"
      - "traefik.docker.network=${NETWORK}_web"
      - "traefik.frontend.rule=PathPrefix:/auth;Host:$HOST"
      - "traefik.enable=true"
      - "traefik.port=8080"
    healthcheck:
      test: curl localhost:8080/auth
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

  # frontend:
  #   image: frontend:latest
  #   restart: always
  #   networks:
  #     - web
  #     - backend
  #   labels:
  #     - "traefik.backend=frontend"
  #     - "traefik.docker.network=${NETWORK}_web"
  #     - "traefik.frontend.rule=PathPrefix:/;Host:$HOST"
  #     - "traefik.enable=true"
  #     - "traefik.port=80"
  #     - "traefik.default.protocol=http"
  #     - "traefik.passHostHeader=true"
  #   healthcheck:
  #     test: curl --fail localhost
  #     interval: 30s
  #     timeout: 3s
  #     retries: 3
  #     start_period: 5s
  frontend:
    image: node:9.11-alpine
    command: 'npm run dev'
    working_dir: /web
    user: node
    environment:
      - PORT=8091
      - HOST=0.0.0.0
    volumes:
      - "../web:/web:ro"
    restart: always
    networks:
      - web
      - backend
    labels:
      - "traefik.backend=frontend"
      - "traefik.docker.network=${NETWORK}_web"
      - "traefik.frontend.rule=PathPrefix:/;Host:$HOST"
      - "traefik.enable=true"
      - "traefik.port=8091"
      - "traefik.default.protocol=http"
      - "traefik.passHostHeader=true"

  traefik:
    image: traefik:1.5.4-alpine
    container_name: traefik
    restart: always
    command: --docker  --api
    ports:
      - "80:80"     #The HTTP port
      - "443:443"
      - "8080:8080" #The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock #So that Traefik can listen to the Docker events
      - ../pkg/traefik/${ENV}.traefik.toml:/traefik.toml:ro
      - ./traefik/acme.json:/acme.json
    networks:
      - web
    labels:
      - "traefik.frontend.rule=Host:$HOST"